version: 2
jobs:
  ios:
    # Specify the Xcode version to use
    macos:
      xcode: 11.4.1

    steps:
      - checkout

      - run:
          name: Install React Native dependencies
          command: |
            brew update
            brew install watchman cocoapods || exit 0
            
      - run:
          name: Install Node dependencies
          command: |
            npm i
            npm i react@16.8.3

      - run:
          name: Run unit tests
          command: npm test

      - run:
          name: Link local copy of cavy
          command: npm link

      - run:
          name: Install command line interfaces
          command: npm install -g cavy-cli react-native-cli

      - run:
          name: Install CavyTester dependencies
          command: |
            mv test ~/
            cd ~/test/CavyTester
            npm i
            npm link cavy
            cd ios
            pod install

      - run:
          name: Link React versions together
          command:
            npm link ../test/CavyTester/node_modules/react

      - run:
          name: Build app and run tests
          command: |
            cd ~/test/CavyTester
            rm -rf $TMPDIR/react-*
            rm -rf $TMPDIR/haste-*
            rm -rf $TMPDIR/metro-*
            watchman watch-del-all
            react-native start --reset-cache --host 127.0.0.1 &
            cavy run-ios

workflows:
  version: 2
  ios:
    jobs:
      - ios
